[package]
name = "png"
version = "0.14.1"
license = "MIT/Apache-2.0"
description = "PNG decoding and encoding library in pure Rust"
authors = ["nwin <nwin@users.noreply.github.com>"]
repository = "https://github.com/image-rs/image-png.git"
edition = "2018"
exclude = [
    "tests/*",
]

[dependencies]
inflate = "0.4.2"
deflate = { version = "0.7.12", optional = true }
num-iter = "0.1.32"
bitflags = "1.0"
crc32fast = "1.2.0"

[dev-dependencies]
getopts = "0.2.14"
term = "0.4"
glob = "0.3"
rand = "0.5.5"
bitbit = "0.2.0"

[dev-dependencies.glium]
version = "0.22"
features = ["glutin"]
default-features = false

[features]
png-encoding = ["deflate"]
default = ["png-encoding"]
unstable = []
benchmarks = []
